apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskmanager-deployment
spec:
  replicas: 1  # Adjust the number of desired replicas as needed
  selector:
    matchLabels:
      app: taskmanager
  template:
    metadata:
      labels:
        app: taskmanager
    spec:
      containers:
      - name: taskmanager
        imagePullPolicy: IfNotPresent
        image: task_manager:latest
        ports:
        - containerPort: 8082  # Adjust the port as needed